import { execFileSync } from "node:child_process"
import { existsSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { config } from "./config.js"

const WORKTREE_DIR = join(config.PROJECT_ROOT, ".worktrees")
const OPEN_PR_CACHE_TTL_MS = 5 * 60 * 1000
let lastKnownOpenPrs: { value: number, updatedAt: number } | null = null
let warnedMissingBaseRef = false

function git(args: string[], options?: { cwd?: string; quietStderr?: boolean; timeout?: number }): string {
  return execFileSync("git", args, {
    cwd: options?.cwd ?? config.PROJECT_ROOT,
    encoding: "utf-8",
    timeout: options?.timeout,
    stdio: ["ignore", "pipe", options?.quietStderr ? "ignore" : "pipe"],
  }).trim()
}

function refExists(ref: string): boolean {
  try {
    execFileSync("git", ["show-ref", "--verify", "--quiet", ref], {
      cwd: config.PROJECT_ROOT,
      stdio: ["ignore", "ignore", "ignore"],
    })
    return true
  } catch {
    return false
  }
}

function resolveBaseRef(): string {
  if (refExists(`refs/heads/${config.BASE_BRANCH}`)) return config.BASE_BRANCH
  if (refExists(`refs/remotes/origin/${config.BASE_BRANCH}`)) return `origin/${config.BASE_BRANCH}`

  if (!warnedMissingBaseRef) {
    console.warn(`[worktree] base branch ${config.BASE_BRANCH} not found, falling back to HEAD`)
    warnedMissingBaseRef = true
  }
  return "HEAD"
}

export function createWorktree(taskId: string): string {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  const branch = `${config.BRANCH_PREFIX}/task-${taskId}`

  // If worktree already exists, reuse it
  if (existsSync(path)) {
    return path
  }

  // If branch exists but worktree doesn't, delete the branch first
  if (refExists(`refs/heads/${branch}`)) {
    git(["branch", "-D", branch], { quietStderr: true })
  }

  git(["worktree", "add", path, "-b", branch, resolveBaseRef()])
  return path
}

export function removeWorktree(taskId: string, keepBranch = false): void {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  if (existsSync(path)) {
    git(["worktree", "remove", path, "--force"])
  }
  if (!keepBranch) {
    const branch = `${config.BRANCH_PREFIX}/task-${taskId}`
    try {
      git(["branch", "-D", branch], { quietStderr: true })
    } catch {
      // branch may already be deleted
    }
  }
}

export function commitWorktree(taskId: string, title: string): string | null {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  try {
    execFileSync("git", ["add", "-A"], { cwd: path, encoding: "utf-8" })
    const status = execFileSync("git", ["status", "--porcelain"], { cwd: path, encoding: "utf-8" }).trim()
    if (status) {
      // unstaged changes remain — commit them
      execFileSync("git", ["commit", "-m", `task-${taskId}: ${title}`], { cwd: path, encoding: "utf-8" })
    }
    // Return HEAD hash whether we committed or Worker already did
    const baseRef = resolveBaseRef()
    const headHash = execFileSync("git", ["rev-parse", "HEAD"], { cwd: path, encoding: "utf-8" }).trim()
    if (baseRef === "HEAD") return headHash
    const mainHash = execFileSync("git", ["rev-parse", baseRef], { cwd: path, encoding: "utf-8" }).trim()
    if (headHash === mainHash) return null // no new commits at all
    return headHash
  } catch (err) {
    console.error(`[worktree] commitWorktree failed for ${taskId}:`, err instanceof Error ? err.message : err)
    return null
  }
}

export function createPullRequest(taskId: string, title: string, facts: { files_changed: string[]; diff_stats: { additions: number; deletions: number } }): string | null {
  const branch = `${config.BRANCH_PREFIX}/task-${taskId}`

  // Push branch to origin
  try {
    execFileSync("git", ["push", "origin", branch], { cwd: config.PROJECT_ROOT, encoding: "utf-8", timeout: 60_000 })
  } catch (err) {
    console.error(`[worktree] push failed for ${branch}:`, err instanceof Error ? err.message : err)
    return null
  }

  // Create PR via gh CLI
  const body = [
    `## Summary`,
    `Task: \`${taskId}\``,
    ``,
    `**Changes:** ${facts.files_changed.length} files (+${facts.diff_stats.additions}/-${facts.diff_stats.deletions})`,
    ``,
    `### Files`,
    ...facts.files_changed.map(f => `- \`${f}\``),
    ``,
    `---`,
    `Auto-generated by DevPane autonomous agent`,
  ].join("\n")

  try {
    const prUrl = execFileSync("gh", [
      "pr", "create",
      "--base", config.BASE_BRANCH,
      "--head", branch,
      "--title", `task-${taskId}: ${title}`,
      "--body", body,
    ], { cwd: config.PROJECT_ROOT, encoding: "utf-8", timeout: 60_000 }).trim()
    return prUrl
  } catch (err) {
    console.error(`[worktree] PR creation failed:`, err instanceof Error ? err.message : err)
    return null
  }
}

export function autoMergePr(taskId: string): boolean {
  const branch = `${config.BRANCH_PREFIX}/task-${taskId}`
  try {
    execFileSync("gh", [
      "pr", "merge", branch,
      config.PR_MERGE_STRATEGY,
    ], { cwd: config.PROJECT_ROOT, encoding: "utf-8", timeout: 30000 })
    return true
  } catch (err) {
    console.error(`[worktree] auto-merge failed for ${branch}:`, err instanceof Error ? err.message : err)
    return false
  }
}

function hasOpenPr(branch: string): boolean {
  try {
    const result = execFileSync("gh", ["pr", "list", "--head", branch, "--state", "open", "--json", "number"], {
      cwd: config.PROJECT_ROOT,
      encoding: "utf-8",
      timeout: 15000,
    }).trim()
    const prs = JSON.parse(result)
    return Array.isArray(prs) && prs.length > 0
  } catch (err) {
    console.warn(`[worktree] Failed to parse JSON output for hasOpenPr(${branch}):`, err instanceof Error ? err.message : err)
    return false
  }
}

export function pruneWorktrees(): void {
  // git worktree prune で壊れた参照を掃除
  git(["worktree", "prune"])

  // .worktreesディレクトリ内の残骸を掃除
  if (!existsSync(WORKTREE_DIR)) return
  const entries = readdirSync(WORKTREE_DIR)
  for (const entry of entries) {
    if (!entry.startsWith("task-") && !entry.startsWith("merge-")) continue
    const path = join(WORKTREE_DIR, entry)
    try {
      git(["worktree", "remove", path, "--force"])
      console.log(`[worktree] pruned stale worktree: ${entry}`)
    } catch {
      // already removed or locked
    }
  }

  // devpane/ プレフィックスの孤立ブランチを掃除
  try {
    const branches = git(["branch", "--list", `${config.BRANCH_PREFIX}/*`]).split("\n").map(b => b.replace(/^[*+]\s+/, "").trim()).filter(Boolean)
    for (const branch of branches) {
      if (hasOpenPr(branch)) {
        console.log(`[worktree] skipping branch with open PR: ${branch}`)
        continue
      }
      try {
        git(["branch", "-D", branch], { quietStderr: true })
        console.log(`[worktree] pruned stale branch: ${branch}`)
      } catch {
        // branch in use
      }
    }
  } catch {
    // no matching branches
  }
}

export function getWorktreeNewAndDeleted(taskId: string): { added: string[]; deleted: string[] } {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  try {
    const mergeBase = execFileSync("git", ["merge-base", "HEAD", resolveBaseRef()], {
      cwd: path,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim()
    const added = execFileSync("git", ["diff", "--diff-filter=A", "--name-only", mergeBase], { cwd: path, encoding: "utf-8" }).trim()
    const deleted = execFileSync("git", ["diff", "--diff-filter=D", "--name-only", mergeBase], { cwd: path, encoding: "utf-8" }).trim()
    return {
      added: added ? added.split("\n") : [],
      deleted: deleted ? deleted.split("\n") : [],
    }
  } catch {
    return { added: [], deleted: [] }
  }
}

export function pullMain(): void {
  try {
    git(["pull", "--ff-only", "origin", config.BASE_BRANCH])
    console.log(`[worktree] pulled latest ${config.BASE_BRANCH}`)
  } catch (err) {
    console.warn(`[worktree] pull ${config.BASE_BRANCH} failed: ${err instanceof Error ? err.message : String(err)}`)
  }
}

export function countOpenPrs(): number | null {
  try {
    const result = execFileSync("gh", ["pr", "list", "--state", "open", "--json", "number"], {
      cwd: config.PROJECT_ROOT,
      encoding: "utf-8",
      timeout: 15000,
    }).trim()
    const prs = JSON.parse(result)
    const count = Array.isArray(prs) ? prs.length : 0
    lastKnownOpenPrs = { value: count, updatedAt: Date.now() }
    return count
  } catch (err) {
    console.warn('[worktree] Failed to parse JSON output for countOpenPrs:', err instanceof Error ? err.message : err)
    if (lastKnownOpenPrs && Date.now() - lastKnownOpenPrs.updatedAt <= OPEN_PR_CACHE_TTL_MS) {
      console.warn(`[worktree] using cached open PR count: ${lastKnownOpenPrs.value}`)
      return lastKnownOpenPrs.value
    }
    return null
  }
}

export function resetOpenPrCountCacheForTests(): void {
  lastKnownOpenPrs = null
}

export function getWorktreeDiff(taskId: string): { filesChanged: string[]; additions: number; deletions: number } {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  try {
    const mergeBase = execFileSync("git", ["merge-base", "HEAD", resolveBaseRef()], {
      cwd: path,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim()
    const nameOnly = execFileSync("git", ["diff", "--name-only", mergeBase], { cwd: path, encoding: "utf-8" }).trim()
    const filesChanged = nameOnly ? nameOnly.split("\n") : []

    const stat = execFileSync("git", ["diff", "--stat", mergeBase], { cwd: path, encoding: "utf-8" }).trim()
    let additions = 0
    let deletions = 0
    const match = stat.match(/(\d+) insertions?\(\+\)/)
    if (match) additions = Number(match[1])
    const match2 = stat.match(/(\d+) deletions?\(-\)/)
    if (match2) deletions = Number(match2[1])

    return { filesChanged, additions, deletions }
  } catch {
    return { filesChanged: [], additions: 0, deletions: 0 }
  }
}

export function resetBaseRefWarningForTests(): void {
  warnedMissingBaseRef = false
}

/**
 * Execute a command in a worktree and parse its JSON output
 * @param taskId The task ID
 * @param command The command to execute
 * @param args Command arguments
 * @returns Parsed JSON result or error object
 */
export function executeInWorktree(
  taskId: string,
  command: string,
  args: string[]
): { success: true; data: unknown } | { success: false; error: string } {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  
  try {
    const stdout = execFileSync(command, args, {
      cwd: path,
      encoding: "utf-8",
      timeout: 30000,
      stdio: ["ignore", "pipe", "pipe"],
    }).trim()
    
    try {
      const data = JSON.parse(stdout)
      return { success: true, data }
    } catch (parseError) {
      console.warn(`[worktree] Failed to parse JSON output from ${command} in worktree ${taskId}:`, 
        parseError instanceof Error ? parseError.message : String(parseError))
      return { success: false, error: 'Failed to parse JSON output' }
    }
  } catch (execError) {
    console.warn(`[worktree] Failed to execute ${command} in worktree ${taskId}:`,
      execError instanceof Error ? execError.message : String(execError))
    return { success: false, error: 'Failed to execute command' }
  }
}
