import { execFileSync } from "node:child_process"
import { existsSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { config } from "./config.js"

const WORKTREE_DIR = join(config.PROJECT_ROOT, ".worktrees")

function git(...args: string[]): string {
  return execFileSync("git", args, { cwd: config.PROJECT_ROOT, encoding: "utf-8" }).trim()
}

export function createWorktree(taskId: string): string {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  const branch = `devpane/task-${taskId}`

  // If worktree already exists, reuse it
  if (existsSync(path)) {
    return path
  }

  // If branch exists but worktree doesn't, delete the branch first
  try {
    git("rev-parse", "--verify", branch)
    git("branch", "-D", branch)
  } catch {
    // branch doesn't exist, good
  }

  git("worktree", "add", path, "-b", branch)
  return path
}

export function removeWorktree(taskId: string, keepBranch = false): void {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  if (existsSync(path)) {
    git("worktree", "remove", path, "--force")
  }
  if (!keepBranch) {
    const branch = `devpane/task-${taskId}`
    try {
      git("branch", "-D", branch)
    } catch {
      // branch may already be deleted
    }
  }
}

export function commitWorktree(taskId: string, title: string): string | null {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  try {
    execFileSync("git", ["add", "-A"], { cwd: path, encoding: "utf-8" })
    const status = execFileSync("git", ["status", "--porcelain"], { cwd: path, encoding: "utf-8" }).trim()
    if (status) {
      // unstaged changes remain — commit them
      execFileSync("git", ["commit", "-m", `task-${taskId}: ${title}`], { cwd: path, encoding: "utf-8" })
    }
    // Return HEAD hash whether we committed or Worker already did
    const mainHash = execFileSync("git", ["rev-parse", "main"], { cwd: path, encoding: "utf-8" }).trim()
    const headHash = execFileSync("git", ["rev-parse", "HEAD"], { cwd: path, encoding: "utf-8" }).trim()
    if (headHash === mainHash) return null // no new commits at all
    return headHash
  } catch (err) {
    console.error(`[worktree] commitWorktree failed for ${taskId}:`, err instanceof Error ? err.message : err)
    return null
  }
}

export function createPullRequest(taskId: string, title: string, facts: { files_changed: string[]; diff_stats: { additions: number; deletions: number } }): string | null {
  const branch = `devpane/task-${taskId}`

  // Push branch to origin
  try {
    execFileSync("git", ["push", "origin", branch], { cwd: config.PROJECT_ROOT, encoding: "utf-8", timeout: 60_000 })
  } catch (err) {
    console.error(`[worktree] push failed for ${branch}:`, err instanceof Error ? err.message : err)
    return null
  }

  // Create PR via gh CLI
  const body = [
    `## Summary`,
    `Task: \`${taskId}\``,
    ``,
    `**Changes:** ${facts.files_changed.length} files (+${facts.diff_stats.additions}/-${facts.diff_stats.deletions})`,
    ``,
    `### Files`,
    ...facts.files_changed.map(f => `- \`${f}\``),
    ``,
    `---`,
    `Auto-generated by DevPane autonomous agent`,
  ].join("\n")

  try {
    const prUrl = execFileSync("gh", [
      "pr", "create",
      "--base", "main",
      "--head", branch,
      "--title", `task-${taskId}: ${title}`,
      "--body", body,
    ], { cwd: config.PROJECT_ROOT, encoding: "utf-8", timeout: 60_000 }).trim()
    return prUrl
  } catch (err) {
    console.error(`[worktree] PR creation failed:`, err instanceof Error ? err.message : err)
    return null
  }
}

export function autoMergePr(taskId: string): boolean {
  const branch = `devpane/task-${taskId}`
  try {
    execFileSync("gh", [
      "pr", "merge", branch,
      "--merge",
    ], { cwd: config.PROJECT_ROOT, encoding: "utf-8", timeout: 30000 })
    return true
  } catch (err) {
    console.error(`[worktree] auto-merge failed for ${branch}:`, err instanceof Error ? err.message : err)
    return false
  }
}

export function pruneWorktrees(): void {
  // git worktree prune で壊れた参照を掃除
  git("worktree", "prune")

  // .worktreesディレクトリ内の残骸を掃除
  if (!existsSync(WORKTREE_DIR)) return
  const entries = readdirSync(WORKTREE_DIR)
  for (const entry of entries) {
    if (!entry.startsWith("task-") && !entry.startsWith("merge-")) continue
    const path = join(WORKTREE_DIR, entry)
    try {
      git("worktree", "remove", path, "--force")
      console.log(`[worktree] pruned stale worktree: ${entry}`)
    } catch {
      // already removed or locked
    }
  }

  // devpane/ プレフィックスの孤立ブランチを掃除
  try {
    const branches = git("branch", "--list", "devpane/*").split("\n").map(b => b.trim()).filter(Boolean)
    for (const branch of branches) {
      try {
        git("branch", "-D", branch)
        console.log(`[worktree] pruned stale branch: ${branch}`)
      } catch {
        // branch in use
      }
    }
  } catch {
    // no matching branches
  }
}

export function getWorktreeNewAndDeleted(taskId: string): { added: string[]; deleted: string[] } {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  try {
    const added = execFileSync("git", ["diff", "--diff-filter=A", "--name-only", "HEAD~1"], { cwd: path, encoding: "utf-8" }).trim()
    const deleted = execFileSync("git", ["diff", "--diff-filter=D", "--name-only", "HEAD~1"], { cwd: path, encoding: "utf-8" }).trim()
    return {
      added: added ? added.split("\n") : [],
      deleted: deleted ? deleted.split("\n") : [],
    }
  } catch {
    return { added: [], deleted: [] }
  }
}

export function pullMain(): void {
  try {
    git("pull", "--ff-only", "origin", "main")
    console.log("[worktree] pulled latest main")
  } catch (err) {
    console.warn(`[worktree] pull main failed: ${err instanceof Error ? err.message : String(err)}`)
  }
}

export function countOpenPrs(): number {
  try {
    const result = execFileSync("gh", ["pr", "list", "--state", "open", "--json", "number"], {
      cwd: config.PROJECT_ROOT,
      encoding: "utf-8",
      timeout: 15000,
    }).trim()
    const prs = JSON.parse(result)
    return Array.isArray(prs) ? prs.length : 0
  } catch (err) {
    console.warn('[worktree] countOpenPrs failed:', err)
    return 0
  }
}

export function getWorktreeDiff(taskId: string): { filesChanged: string[]; additions: number; deletions: number } {
  const path = join(WORKTREE_DIR, `task-${taskId}`)
  try {
    const nameOnly = execFileSync("git", ["diff", "--name-only", "HEAD~1"], { cwd: path, encoding: "utf-8" }).trim()
    const filesChanged = nameOnly ? nameOnly.split("\n") : []

    const stat = execFileSync("git", ["diff", "--stat", "HEAD~1"], { cwd: path, encoding: "utf-8" }).trim()
    let additions = 0
    let deletions = 0
    const match = stat.match(/(\d+) insertions?\(\+\)/)
    if (match) additions = Number(match[1])
    const match2 = stat.match(/(\d+) deletions?\(-\)/)
    if (match2) deletions = Number(match2[1])

    return { filesChanged, additions, deletions }
  } catch {
    return { filesChanged: [], additions: 0, deletions: 0 }
  }
}
